// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviePlatform.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoviePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(MoviePlatformDbContext))]
    partial class MoviePlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoviePlatform.Domain.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("movie_id");

                    b.Property<double>("AverageScore")
                        .HasPrecision(2, 1)
                        .HasColumnType("double precision")
                        .HasColumnName("average_score");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("genre");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("movies", null, t =>
                        {
                            t.HasCheckConstraint("CK_movies_average_score_range", "average_score = 0 OR (average_score >= 1 AND average_score <= 5)");

                            t.HasCheckConstraint("CK_movies_review_count_not_negative", "review_count >= 0");

                            t.HasCheckConstraint("CK_movies_title_not_empty", "length(title) > 0");
                        });
                });

            modelBuilder.Entity("MoviePlatform.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email_unique");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_email_not_empty", "length(email) > 0");

                            t.HasCheckConstraint("CK_users_name_not_empty", "length(name) > 0");

                            t.HasCheckConstraint("CK_users_password_hash_not_empty", "length(password_hash) > 0");
                        });
                });

            modelBuilder.Entity("MoviePlatform.Domain.Movies.Movie", b =>
                {
                    b.OwnsMany("MoviePlatform.Domain.Movies.Entities.Comment", "Comments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("comment_id");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("content");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid")
                                .HasColumnName("movie_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id");

                            b1.HasIndex("MovieId");

                            b1.ToTable("comments", null, t =>
                                {
                                    t.HasCheckConstraint("CK_comments_content_not_empty", "length(content) > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.OwnsMany("MoviePlatform.Domain.Movies.Entities.Review", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("review_id");

                            b1.Property<DateTimeOffset>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at_utc");

                            b1.Property<Guid>("MovieId")
                                .HasColumnType("uuid")
                                .HasColumnName("movie_id");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("score");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id");

                            b1.HasIndex("MovieId", "UserId")
                                .IsUnique()
                                .HasDatabaseName("IX_reviews_movie_id_user_id_unique");

                            b1.ToTable("reviews", null, t =>
                                {
                                    t.HasCheckConstraint("CK_reviews_score_range", "score >= 1 AND score <= 5");
                                });

                            b1.WithOwner()
                                .HasForeignKey("MovieId");
                        });

                    b.Navigation("Comments");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
